# Generated by Django 4.0.4 on 2022-05-12 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Recepy',
        ),
    ]
