# Generated by Django 4.0.4 on 2022-05-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0002_rename_car_recepy'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepy',
            name='author',
            field=models.CharField(default='Author unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='recepy',
            name='publication',
            field=models.DateTimeField(default='date is uknonw'),
        ),
        migrations.AddField(
            model_name='recepy',
            name='tags',
            field=models.TextField(default='dish', max_length=300),
        ),
    ]
