# Generated by Django 4.0.4 on 2022-05-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0003_recepy_author_recepy_publication_recepy_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepy',
            name='publication',
            field=models.DateTimeField(default='2022-05-29'),
        ),
    ]
