# Generated by Django 4.0.4 on 2022-06-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0003_recepy_author_recepy_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('secondName', models.CharField(max_length=20)),
                ('info', models.TextField(max_length=600)),
            ],
        ),
        migrations.AlterField(
            model_name='recepy',
            name='tags',
            field=models.TextField(default='dish, choice = tags_choice', max_length=300),
        ),
    ]
