# Generated by Django 4.0.4 on 2022-05-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0004_alter_recepy_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepy',
            name='publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
