# Generated by Django 4.0.4 on 2022-05-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0005_alter_recepy_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepy',
            name='publication',
        ),
        migrations.AlterField(
            model_name='recepy',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recepy',
            name='tags',
            field=models.TextField(max_length=300),
        ),
    ]
